DEBUG 2022-02-23 23:32:52.369 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-23 23:32:52.369 UTC: 	 Running on: Linux lxplus7112.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-23 23:32:52.369 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-23 23:32:52.369 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-23 23:32:52.370 UTC: 	 Will use CRAB configuration file CRAB_Production_23_02_22_AlCaPhiSym_Run2018D-v1_RAW_0.py
DEBUG 2022-02-23 23:32:52.370 UTC: 	 Loading CRAB configuration file.
ERROR 2022-02-23 23:32:52.375 UTC: 	 Invalid CRAB configuration: Parameter Data.unitsPerJob must be > 0, not -1.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2022-02-23 23:32:52.375 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 94, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.unitsPerJob must be > 0, not -1.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2022-02-23 23:32:52.379 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-23 23:33:24.958 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-23 23:33:24.959 UTC: 	 Running on: Linux lxplus7112.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-23 23:33:24.959 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-23 23:33:24.959 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-23 23:33:24.960 UTC: 	 Will use CRAB configuration file CRAB_Production_23_02_22_AlCaPhiSym_Run2018D-v1_RAW_0.py
DEBUG 2022-02-23 23:33:24.960 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-02-23 23:33:25.196 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-02-23 23:33:25.197 UTC: 	 Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_23_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW' already exists 
Please change the requestName in the config file
ERROR 2022-02-23 23:33:25.197 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_23_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW' already exists 
Please change the requestName in the config file
INFO 2022-02-23 23:33:25.200 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-24 19:51:25.656 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-24 19:51:25.657 UTC: 	 Running on: Linux lxplus724.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-24 19:51:25.657 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-24 19:51:25.657 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-24 19:51:25.658 UTC: 	 Will use CRAB configuration file CRAB_Production_23_02_22_AlCaPhiSym_Run2018D-v1_RAW_0.py
DEBUG 2022-02-24 19:51:25.658 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-02-24 19:51:25.673 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-02-24 19:51:25.673 UTC: 	 Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_23_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
ERROR 2022-02-24 19:51:25.673 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_23_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
INFO 2022-02-24 19:51:25.692 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-24 19:53:51.571 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-24 19:53:51.571 UTC: 	 Running on: Linux lxplus724.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-24 19:53:51.572 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-24 19:53:51.572 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-24 19:53:51.582 UTC: 	 Will use CRAB configuration file CRAB_Production_23_02_22_AlCaPhiSym_Run2018D-v1_RAW_0.py
DEBUG 2022-02-24 19:53:51.582 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-02-24 19:53:51.592 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-02-24 19:53:51.592 UTC: 	 Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_23_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
ERROR 2022-02-24 19:53:51.592 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_23_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
INFO 2022-02-24 19:53:51.596 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-24 20:20:45.246 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-24 20:20:45.247 UTC: 	 Running on: Linux lxplus724.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-24 20:20:45.247 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-24 20:20:45.247 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
ERROR 2022-02-24 20:20:45.248 UTC: 	 CRAB configuration file crab not found.
ERROR 2022-02-24 20:20:45.248 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 51, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab not found.
INFO 2022-02-24 20:20:45.267 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-25 14:05:59.239 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-25 14:05:59.239 UTC: 	 Running on: Linux lxplus767.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-25 14:05:59.239 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-25 14:05:59.239 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-25 14:05:59.241 UTC: 	 Will use CRAB configuration file CRAB_Production_25_02_22_AlCaPhiSym_Run2018D-v1_RAW_0.py
DEBUG 2022-02-25 14:05:59.241 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-02-25 14:05:59.247 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-02-25 14:05:59.248 UTC: 	 Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
ERROR 2022-02-25 14:05:59.248 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_22/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
INFO 2022-02-25 14:05:59.284 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-25 19:17:29.374 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-25 19:17:29.375 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-25 19:17:29.375 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-25 19:17:29.375 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-25 19:17:29.376 UTC: 	 Will use CRAB configuration file CRAB_Production_25_02_2022_AlCaPhiSym_Run2018D-v1_RAW_0.py
DEBUG 2022-02-25 19:17:29.376 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-02-25 19:17:29.450 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-02-25 19:17:29.451 UTC: 	 Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_2022/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
ERROR 2022-02-25 19:17:29.451 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_2022/crab_AlCaPhiSym_Run2018D-v1_RAW_0' already exists 
Please change the requestName in the config file
INFO 2022-02-25 19:17:29.585 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-25 19:18:51.543 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-25 19:18:51.543 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-25 19:18:51.543 UTC: 	 Executing command: 'status'
DEBUG 2022-02-25 19:18:51.543 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
ERROR 2022-02-25 19:18:51.545 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_2022/crab_AlCaPhiSym_Run2018D-v1_RAW_0
ERROR 2022-02-25 19:18:51.545 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_2022/crab_AlCaPhiSym_Run2018D-v1_RAW_0
INFO 2022-02-25 19:18:51.548 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-25 19:40:29.163 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-25 19:40:29.163 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-25 19:40:29.163 UTC: 	 Executing command: 'checkwrite'
DEBUG 2022-02-25 19:40:29.163 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
WARNING 2022-02-25 19:40:29.164 UTC: 	 Warning: 'crab checkwrite' command takes no arguments, 1 given. Ignoring arguments ['T2_CH_CERN'].
DEBUG 2022-02-25 19:40:29.164 UTC: 	 Checking credentials
DEBUG 2022-02-25 19:40:29.165 UTC: 	 Found proxy file /afs/cern.ch/user/b/bjoshi/x509up_u92327
DEBUG 2022-02-25 19:40:29.165 UTC: 	 Making sure it has proper VOMS extension
DEBUG 2022-02-25 19:40:29.165 UTC: 	 Executing command :
 voms-proxy-info --vo --file /afs/cern.ch/user/b/bjoshi/x509up_u92327
DEBUG 2022-02-25 19:40:29.863 UTC: 	 output : cms

 error: 
 retcode : 0
DEBUG 2022-02-25 19:40:29.863 UTC: 	 Getting proxy life time left
DEBUG 2022-02-25 19:40:29.863 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /afs/cern.ch/user/b/bjoshi/x509up_u92327
DEBUG 2022-02-25 19:40:30.482 UTC: 	 output : 40863
40862

 error: 
 retcode : 0
DEBUG 2022-02-25 19:40:30.482 UTC: 	 Proxy valid for 11:21:02 hours
ERROR 2022-02-25 19:40:30.483 UTC: 	 Error: Please specify the site where to check the write permissions. Use the --site option.
ERROR 2022-02-25 19:40:30.483 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/checkwrite.py", line 20, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 378, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/checkwrite.py", line 291, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please specify the site where to check the write permissions. Use the --site option.
INFO 2022-02-25 19:40:30.539 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
DEBUG 2022-02-25 19:40:42.016 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-25 19:40:42.016 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-25 19:40:42.016 UTC: 	 Executing command: 'checkwrite'
DEBUG 2022-02-25 19:40:42.016 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
DEBUG 2022-02-25 19:40:42.017 UTC: 	 Checking credentials
DEBUG 2022-02-25 19:40:42.017 UTC: 	 Found proxy file /afs/cern.ch/user/b/bjoshi/x509up_u92327
DEBUG 2022-02-25 19:40:42.017 UTC: 	 Making sure it has proper VOMS extension
DEBUG 2022-02-25 19:40:42.018 UTC: 	 Executing command :
 voms-proxy-info --vo --file /afs/cern.ch/user/b/bjoshi/x509up_u92327
DEBUG 2022-02-25 19:40:42.686 UTC: 	 output : cms

 error: 
 retcode : 0
DEBUG 2022-02-25 19:40:42.686 UTC: 	 Getting proxy life time left
DEBUG 2022-02-25 19:40:42.686 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /afs/cern.ch/user/b/bjoshi/x509up_u92327
DEBUG 2022-02-25 19:40:43.331 UTC: 	 output : 40850
40849

 error: 
 retcode : 0
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Proxy valid for 11:20:49 hours
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Command use: checkwrite
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Options use: ['--site', 'T2_CH_CERN']
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Instance is None
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Server base url is None
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Retrieving username ...
DEBUG 2022-02-25 19:40:43.332 UTC: 	 Retrieving username from CRIC...
DEBUG 2022-02-25 19:40:44.135 UTC: 	 username is bjoshi
INFO 2022-02-25 19:40:44.135 UTC: 	 Will check write permission in the default location /store/user/<username>
INFO 2022-02-25 19:40:44.136 UTC: 	 Validating LFN /store/user/bjoshi...
INFO 2022-02-25 19:40:44.136 UTC: 	 LFN /store/user/bjoshi is valid.
INFO 2022-02-25 19:40:44.152 UTC: 	 Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
INFO 2022-02-25 19:40:44.153 UTC: 	 Will check write permission in /store/user/bjoshi on site T2_CH_CERN
INFO 2022-02-25 19:40:45.946 UTC: 	 Will use PFN: rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/crab3checkwrite_20220225_204044.tmp
INFO 2022-02-25 19:40:45.947 UTC: 	 
Attempting to create (dummy) directory crab3checkwrite_20220225_204044 and copy (dummy) file crab3checkwrite_20220225_204044.tmp to /store/user/bjoshi

INFO 2022-02-25 19:40:45.952 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 file:///afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab3checkwrite_20220225_204044.tmp 'rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/crab3checkwrite_20220225_204044.tmp'
INFO 2022-02-25 19:40:45.952 UTC: 	 Please wait...
INFO 2022-02-25 19:40:46.544 UTC: 	 
Successfully created directory crab3checkwrite_20220225_204044 and copied file crab3checkwrite_20220225_204044.tmp to /store/user/bjoshi
INFO 2022-02-25 19:40:46.545 UTC: 	 
Attempting to delete file rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/crab3checkwrite_20220225_204044.tmp

INFO 2022-02-25 19:40:46.545 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/crab3checkwrite_20220225_204044.tmp'
INFO 2022-02-25 19:40:46.545 UTC: 	 Please wait...
INFO 2022-02-25 19:40:46.971 UTC: 	 
Successfully deleted file rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/crab3checkwrite_20220225_204044.tmp
INFO 2022-02-25 19:40:46.971 UTC: 	 
Attempting to delete directory rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/

INFO 2022-02-25 19:40:46.971 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/'
INFO 2022-02-25 19:40:46.971 UTC: 	 Please wait...
INFO 2022-02-25 19:40:47.289 UTC: 	 
Successfully deleted directory rucio 1.27.2
davs://eoscms.cern.ch:443//eos/cms/store/user/bjoshi/crab3checkwrite_20220225_204044/
INFO 2022-02-25 19:40:47.334 UTC: 	 
Checkwrite Result:
INFO 2022-02-25 19:40:47.334 UTC: 	 Success: Able to write in /store/user/bjoshi on site T2_CH_CERN
DEBUG 2022-02-25 19:48:08.688 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-02-25 19:48:08.688 UTC: 	 Running on: Linux lxplus795.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-02-25 19:48:08.688 UTC: 	 Executing command: 'submit'
DEBUG 2022-02-25 19:48:08.688 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bjoshi/.crab3
INFO 2022-02-25 19:48:08.689 UTC: 	 Will use CRAB configuration file CRAB_Production_25_02_2022_AlCaPhiSym_Run2018D-v1_RAW_1.py
DEBUG 2022-02-25 19:48:08.689 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-02-25 19:48:08.762 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-02-25 19:48:08.762 UTC: 	 Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_2022/crab_AlCaPhiSym_Run2018D-v1_RAW_1' already exists 
Please change the requestName in the config file
ERROR 2022-02-25 19:48:08.762 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab_projects/Production_25_02_2022/crab_AlCaPhiSym_Run2018D-v1_RAW_1' already exists 
Please change the requestName in the config file
INFO 2022-02-25 19:48:08.766 UTC: 	 Log file is /afs/cern.ch/work/b/bjoshi/Analysis/UMN/CMSSW_10_6_14/src/EcalTiming/EcalTiming/crab/crab.log
